name: tests
on:
  workflow_dispatch:
  workflow_call:
jobs:
  code-edit-text-view-tests:
    name: Testing CodeEditLanguages
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS files
        run: git lfs checkout
      - name: Testing Package
        run: exec ./.github/scripts/tests.sh arm
